import { execSync } from "child_process";
import { Command } from "commander";
import fs from "fs";
import readLine from "readline-sync";
import { ALIASES_PATH, BKP_DIR, NOW, ZSHRC_PATH } from "./envs";
import packageInfo from "./package.json";


const app = new Command()
app
  .name('aliases')
  .description('CLI add alias on .zshrc')
  .version(packageInfo.version)
  .requiredOption('-n, --name <string>', 'name of alias')
  .requiredOption('-c, --command <string>', 'command for said alias')
  .option('-p, --preview', 'if option is used the changes not be write on the .zshrc file', false)

app.parse()

const flags = app.opts()
const preview = !!flags.preview
const name = flags.name
const command = flags.command

!name || !command && app.help()

const bkpDirExists = fs.existsSync(BKP_DIR)
!bkpDirExists && fs.mkdirSync(BKP_DIR)

try {
  fs.copyFileSync(ZSHRC_PATH, `${BKP_DIR}/zshrc_${NOW}`)
} catch (error) {
  error instanceof Error && app.error(error.message)
}

try {
  const zshrcContent = fs.readFileSync(ZSHRC_PATH).toLocaleString()
  const header = '# BEGIN - GENERATED BY ADD-ALIAS CLI'
  const content = 'source $HOME/.aliases'
  !zshrcContent.includes(header) && fs.appendFileSync(ZSHRC_PATH, `\n${header}`)
  !zshrcContent.includes(content) && fs.appendFileSync(ZSHRC_PATH, `\n${content}`)
} catch (error) {
  error instanceof Error && app.error(error.message)
}

try {
  const alias = `alias ${name}="${command}"`
  const aliasesContent = fs.readFileSync(ALIASES_PATH).toLocaleString()
  const lines = aliasesContent.split('\n')
  const lastLine = lines[lines.length - 1]
  const lastLineIsBlank = lastLine == ""

  execSync(`sed -i '/^$/d' ${ALIASES_PATH}`)
  if (aliasesContent.includes(`alias ${name}`, 1)) {
    !readLine.keyInYN('This alias already exists. Do you want to update?') && app.exitOverride()
    execSync(`sed -i '/^alias ${name}=/d' ${ALIASES_PATH}`)
  }

  !lastLineIsBlank && fs.appendFileSync(ALIASES_PATH, "\n")
  fs.appendFileSync(ALIASES_PATH, alias)
  execSync(alias)
} catch (error) {
  error instanceof Error && app.error(error.message)
}
