import chalk from "chalk"
import fs from "fs"
import { BKP_DIR, NOW, RELOAD_MESSAGE, RC_FILE_PATH } from "./envs"

export default () => {
    const bkpDirExists = fs.existsSync(BKP_DIR)
    !bkpDirExists && fs.mkdirSync(BKP_DIR)

    try {
        fs.copyFileSync(RC_FILE_PATH, `${BKP_DIR}/zshrc_${NOW}`)
    } catch (error) {
        if (error instanceof Error) {
            console.error(error.message)
            process.exit(1)
        }
    }

    try {
        const rcFileContent = fs.readFileSync(RC_FILE_PATH).toLocaleString()
        const header = '# BEGIN - GENERATED BY ALIASES CLI'
        const source = 'source $HOME/.aliases'
        const reload_aliases_fn = `reload_aliases() {
            source ~/.aliases
        }`
        const content = `\n${header}\n${reload_aliases_fn}\n${source}`
        if (!rcFileContent.includes(content)) {
            fs.appendFileSync(RC_FILE_PATH, content)
            console.log(`${chalk.yellow(RELOAD_MESSAGE)}.`)
            process.exit()
        }
    } catch (error) {
        if (error instanceof Error) {
            console.error(error.message)
            process.exit(1)

        }
    }

}