import type { Command } from "commander"
import fs from "fs"
import { BKP_DIR, NOW, ZSHRC_PATH } from "./envs"

export default () => {
    const bkpDirExists = fs.existsSync(BKP_DIR)
    !bkpDirExists && fs.mkdirSync(BKP_DIR)

    try {
        fs.copyFileSync(ZSHRC_PATH, `${BKP_DIR}/zshrc_${NOW}`)
    } catch (error) {
        if (error instanceof Error) {
            console.error(error.message)
            process.exit(1)
        }
    }

    try {
        const zshrcContent = fs.readFileSync(ZSHRC_PATH).toLocaleString()
        const header = '# BEGIN - GENERATED BY ALIASES CLI'
        const fn = `aliases() {
            eval $(npx aliases "$@")
        }`
        const source = 'source $HOME/.aliases'
        if (!zshrcContent.includes(header)) {
            fs.appendFileSync(ZSHRC_PATH, `\n${header}\n${fn}\n${source}`)
            console.log('Reload the terminal for the changes to take effect')
            process.exit()
        }
    } catch (error) {
        if (error instanceof Error) {
            console.error(error.message)
            process.exit(1)

        }
    }

}