import type { Command } from "commander"
import fs from "fs"
import { BKP_DIR, NOW, ZSHRC_PATH } from "./envs"

export default (app: Command) => {
    const bkpDirExists = fs.existsSync(BKP_DIR)
    !bkpDirExists && fs.mkdirSync(BKP_DIR)

    try {
        fs.copyFileSync(ZSHRC_PATH, `${BKP_DIR}/zshrc_${NOW}`)
    } catch (error) {
        error instanceof Error && app.error(error.message)
    }

    try {
        const zshrcContent = fs.readFileSync(ZSHRC_PATH).toLocaleString()
        const header = '# BEGIN - GENERATED BY ALIASES CLI'
        const content = 'source $HOME/.aliases'
        !zshrcContent.includes(header) && fs.appendFileSync(ZSHRC_PATH, `\n${header}`)
        !zshrcContent.includes(content) && fs.appendFileSync(ZSHRC_PATH, `\n${content}`)
    } catch (error) {
        error instanceof Error && app.error(error.message)
    }

}